config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :admin_users
    resources :spents
    resources :wallets
    root to: "users#index"
  end

  resources :wallets
  resources :spents
  devise_for :users
  # resources :admin_users
  get 'static/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#home'
end

app/models/AdminUser.rb
class AdminUser < User

end

app/models/Admin_User.rb
class AdminUser < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spent.rb
class Spent < ApplicationRecord
  enum status: { open: 0, submitted: 1, approved: 2, rejected: 3 }
	belongs_to :user
	validates_presence_of :value, :date, :description

end

app/models/user.rb
class User < ApplicationRecord
  has_many :spents

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
    first_name + ' ' + last_name
  end

end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin
    #Only allow authenticate users to see this route
    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page"
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/spents_controller.rb
module Admin
  class SpentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Spent.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Spent.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/wallets_controller.rb
module Admin
  class WalletsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Wallet.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Wallet.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/spents_controller.rb
class SpentsController < ApplicationController
  before_action :set_spent, only:[:show, :edit, :update, :destroy]

  def index
    @spents = Spent.all
  end

  def new
    @spent = Spent.new
  end

  def create
    @spent = Spent.new(spent_params)
    @spent.user_id = current_user.id

    if @spent.save
      redirect_to spents_path, notice: 'Your spent was created sucessfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
  if @spent.update(spent_params)
    redirect_to @spent, notice: 'Your post was created successfully'
  else
    render :edit
  end
end

  def show

  end

  def destroy
    @spent.destroy
    redirect_to spents_path, notice: 'Your spent was destroyed sucessfully'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def spent_params
    params.require(:spent).permit(:value, :date, :description, :status)
  end

  def set_spent
     @spent = Spent.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: [:show, :edit, :update, :destroy]

  # GET /wallets
  # GET /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1
  # GET /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets
  # POST /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: 'Wallet was successfully created.' }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1
  # PATCH/PUT /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: 'Wallet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallet_params
      params.require(:wallet).permit(:name, :total, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
	  "active" if current_page?(path)
	end
end

app/helpers/spents_helper.rb
module SpentsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/admin/applications/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
      " scope="col">
        <%= link_to(sanitized_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/applications/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/applications/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "Edit #{page.page_title}" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "Show #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<%= render "form", page: page %>

app/views/admin/applications/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="Search"
      value="<%= search_term %>"
      aria-label="Search"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/admin/applications/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "New #{page.resource_name.titleize}" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to 'Back', :back, class: "button" %>
  </div>
</header>

<%= render 'form', page: page %>

app/views/admin/applications/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.page_title } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "Edit",
      [:edit, namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<dl>
  <% page.attributes.each do |attribute| %>
    <dt class="attribute-label">
    <%= t(
      "helpers.label.#{resource_name}.#{attribute.name}",
      default: attribute.name.titleize,
    ) %>
    </dt>

    <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
        ><%= render_field attribute %></dd>
  <% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Control app</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <%= render 'shared/navbar' %> -->
  </head>

  <body >
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav' %>
          <%= yield %>
        </div>
      </div>
    </div>
   <%= js add_gritter(flash[:notice], title: "wmm app Notification", sticky: false, time: 3000) %>
  </body>

</html>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<div class='logo'>
	<h1>Where is my monkey?</h1>
</div>

<div class="container">
<% if current_user %>
<ul class="custom_nav nav nav-tabs">
	<li class="<%= active?(root_path) %>">
		<%= link_to "Home", root_path %>
	</li>
	<li class="<%= active?(root_path) %>">
		<%= link_to "Spents Entries", spents_path %>
	</li>
	<li class="<%= active?(root_path) %>">
		<%= link_to "Add new Entrie", new_spent_path, id: "new_post_from_nav" %>
	</li>
	<li class="<%= active?(root_path) %>">
		<%= link_to "Wallets", wallets_path %>
	</li>

	<li class="dropdown pull-right">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle"> Options <strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "Edit User", edit_user_registration_path %>
			</li>
           
		   <% if current_user.try(:type) == 'AdminUser' %>
			<li>
				<%= link_to "Admin Dashboard", admin_root_path %>
			</li>
			<li class="divider"></li>
           <% end %>

			<li>
				<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			</li>
		</ul>
	</li>
</ul>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		</button> <a class="navbar-brand" href="#">Where is my money?!</a>
	</div>

	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

		<ul class="nav navbar-nav">
			<li class="active"><a href="#">Link</a></li>
			<li><a href="#">Admin</a></li>
			<li class="dropdown">
				 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li class="divider"></li>
					<li><a href="#">Separated link</a></li>
					<li class="divider"></li>
					<li><a href="#">One more separated link</a></li>
				</ul>
			</li>
		</ul>

		<form class="navbar-form navbar-left" role="search">
			<div class="form-group">
               <input type="text" class="form-control" />
			</div>
			<button type="submit" class="btn btn-default">
				Go!
			</button>
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li><a href="#">Link</a></li>

			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li class="divider">
					</li>
					<li><a href="#">Separated link</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>

app/views/shared/_progressbar.html.erb
<div class="container">
Goal
<div class="progress progress-striped active">
    <div class="progress-bar" style="width: 90%;">
        <span class="sr-only">90% Complete</span>
    </div>
</div>
</div>

app/views/spents/_form.html.erb
<%= form_for @spent, class:"form-horizontal" do |f| %>

  <% if @spent.errors.any? %>
    <% @spent.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "App Notification", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
      <%= f.label :value, class: "col-sm-2 control-label" %>
      <%= f.text_field :value, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <%= f.date_field :date, class: "form-control" %>
  <div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <%= f.text_area :description, class: "form-control" %>
  <div>

  <%= render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser' %>

  <hr>
  <%= f.submit 'Save', class: "btn btn-primary btn-block" %>
<% end %>

app/views/spents/_spent.html.erb
<tr>
<td><%= spent.id %></td>
<td><%= spent.status %></td>
<td><%= spent.value %></td>
<td><%= spent.date %></td>
<td><%= spent.description %></td>
<td><%= spent.user.full_name %></td>

<td>
  <%= link_to t('.show', :default => t("helpers.links.show")),
              spents_path(spent), :class => 'btn btn-default btn-xs' %>

  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_spent_path(spent),
              id: "edit_#{spent.id}",
              :class => 'btn btn-default btn-xs' %>

  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              spent_path(spent),
              :method => :delete,
              id: "delete_post_#{spent.id}_from_index",
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
</td>
</tr>

app/views/spents/_status.html.erb
<div class="form-group">
    <%= f.radio_button :status, 'submitted' %>
    <%= f.label :status, 'Submitted' %>
    <%= f.radio_button :status, 'approved' %>
    <%= f.label :status, 'Approved' %>
    <%= f.radio_button :status, 'rejected' %>
    <%= f.label :status, 'Rejected' %>
</div>

app/views/spents/edit.html.erb
<%- model_class = Spent -%>
<div class="page-header">
 <h1><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/spents/index.html.erb
<h1>Spents</h1>

<table class="table table-hover table-striped">
<thead>
<tr>
	<th>#</th>
	<th>Value</th>
	<th>Date</th>
	<th>description</th>
	<th>username</th>
</tr>
</thead>
<tbody>
	<!-- <div class="row"> -->
	<%= link_to 'New Spent', new_spent_path, class: "btn btn-primary" %>
  <!-- <div class="row"> -->
    <!-- <%= render 'shared/progressbar' %> -->
  <!-- </div> -->
	<div class="row">
	    <%= render @spents %>
	</div>

</body>
</table>

</div>

app/views/spents/new.html.erb
 <%- model_class = Spent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/spents/show.html.erb
<%= @spent.inspect %>

app/views/wallets/_form.html.erb
<%= form_for @wallet, class: "form-horizontal" do |f| %>

  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :total, class: "col-sm-2 control-label" %>
    <%= f.text_field :total, class: "form-control" %>
  </div>

  <%= f.select(:user_id,
               User.order(:email).collect {|user| [user.email, user.id]},
               {include_blank: "Select User"},
               {class: "form-control"} ) %>
  <hr>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/wallets/_wallet.html.erb
<tr>
  <td><%= wallet.name %></td>
  <td><%= wallet.total %></td>
  <td><%= wallet.user.full_name %></td>


  <td>
      <%= link_to t('.show', :default => t("helpers.links.show")),
                  wallets_path(wallet), :class => 'btn btn-default btn-xs' %>

      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_wallet_path(wallet), :class => 'btn btn-default btn-xs' %>

      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  wallet_path(wallet),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
    </td>
</tr>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallets</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div class="row">
        <%= render 'shared/progressbar' %>
    </div>
	<div class="row">
    <%= render @wallets %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet', new_wallet_path %>

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wallet.name %>
</p>

<p>
  <strong>Total:</strong>
  <%= @wallet.total %>
</p>

<p>
  <strong>User:</strong>
  <%= @wallet.user %>
</p>

<%= link_to 'Edit', edit_wallet_path(@wallet) %> |
<%= link_to 'Back', wallets_path %>